### ISSUE TITLE
InfluxDB HTTP 400

### ISSUE THREAD

**Issue by Seji64** [sensu-extensions/sensu-extensions-influxdb2#18]
Hi,

i just noticed on my InfluxDB Host log messages like this:
```
[httpd] 10.195.160.23 - sensu [08/Nov/2017:13:31:12 +0100] "POST /write?db=sensu&p=%5BREDACTED%5D&precision=s&u=sensu HTTP/1.1" 400 300 "-" "EventMachine HttpClient" b4fa1f0d-c480-11e7-b3e2-000000000000 6003
```

They occure multiple times. Is this 'normal' ? Sensu is only logging that all is ok.

Thanks in advance.

- Seji

PS: I'am running Sensu 1.1.1 and InfluxDB 1.3.5 on CentOS 7.4

**Comment by alcasim** [comment]
@Seji64 I have noticed those 400 then something was wrong in the posted data to InfluxDB (in my case, it was a duplicated tag). The metrics were missing as they were not inserted in InfluxDB so you might want to review your tags and look for a duplicate (the extension is not controlling this).

I also think it might be useful to get a better output of what's going on with InfluxDB on the extension (preferably on debug log level), as InfluxDB is sometimes obscure in its responses (to discover my problem I had to locally modify the extension adding output posted to InfluxDB into a file, then trying that output by myself to get an error message with the problem).

I hope that helps.

**Comment by Seji64** [comment]
Hi alcasim,

first of all - thanks for your answer.

Concerning the double tags - I don't quite understand that.

For example, I have this check:

```
{
        "checks": {
                "metric-mariadb": {
                "type": "metric",
                "command": "/opt/sensu/embedded/bin/metrics-mysql-graphite.rb --host=:::name::: --ini=/etc/sensu/mysql.ini",
                "subscribers": ["mariadb-default"],
                "interval": 30,
                "handlers": ["metrics"],
                "influxdb": {
                    "tags": { "service": "mariadb"},
                    "templates":{
                        "mysql\\..*\\.*": "measurement.void.instance.field*"
                     }
                 }
            }
      }
}
```

But I now have 3 MySQL servers that subscribe to this check - so I would have "duplicate" tags?

**Comment by Seji64** [comment]
With some tcpdump and wireshark magic i found my metric check which caused this issue. I would be great if this extension checks the return code.
