### ISSUE TITLE
Rename sensu-extensions-influxdb to sensu-extensions-influxdb2

### ISSUE THREAD

**Issue by neyz** [sensu-extensions/sensu-extensions-influxdb2#4]
I'm not quite sure how to formulate this because i'm really quite new to sensu but trying to load this extension crashes my instance. I tried to follow the readme file to the letter.

Using sensu 0.29.0-11 on Debian Jessie.

Here is the end of the sensu-server log, please tell me if i can do anything else.
```json
{"timestamp":"2017-07-05T15:05:53.984292+0000","level":"warn","message":"loading extension files from directory","directory":"/etc/sensu/extensions"}
{"timestamp":"2017-07-05T15:05:53.984503+0000","level":"warn","message":"loading extension gem","gem":"sensu-extensions-influxdb","version":null}
{"timestamp":"2017-07-05T15:05:53.984540+0000","level":"warn","message":"requiring extension gem","require":"sensu/extensions/influxdb"}
{"timestamp":"2017-07-05T15:05:53.984563+0000","level":"warn","message":"loading extension gem","gem":"sensu-extensions-history","version":null}
{"timestamp":"2017-07-05T15:05:53.984587+0000","level":"warn","message":"requiring extension gem","require":"sensu/extensions/history"}
{"timestamp":"2017-07-05T15:05:53.984606+0000","level":"warn","message":"failed to require extension","gem":"sensu-extensions-history","version":null,"error":{"path":"sensu/extensions/history","~bt_locations":"#<Thread::Backtrace:0x00000002572dd8>","~mesg":"cannot load such file -- sensu/extensions/history","~bt":["/opt/sensu/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'","/opt/sensu/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'","/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-extensions-1.9.0/lib/sensu/extensions/loader.rb:117:in `load_gem'","/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-extensions-1.9.0/lib/sensu/extensions.rb:30:in `block in load'","/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-extensions-1.9.0/lib/sensu/extensions.rb:28:in `each'","/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-extensions-1.9.0/lib/sensu/extensions.rb:28:in `load'","/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-extensions-1.9.0/lib/sensu/extensions.rb:44:in `get'","/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-0.29.0/lib/sensu/daemon.rb:158:in `load_extensions'","/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-0.29.0/lib/sensu/daemon.rb:58:in `initialize'","/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-0.29.0/lib/sensu/server/process.rb:44:in `initialize'","/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-0.29.0/lib/sensu/server/process.rb:32:in `new'","/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-0.29.0/lib/sensu/server/process.rb:32:in `run'","/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-0.29.0/exe/sensu-server:10:in `<top (required)>'","/opt/sensu/bin/sensu-server:22:in `load'","/opt/sensu/bin/sensu-server:22:in `<main>'"]}}
{"timestamp":"2017-07-05T15:05:53.985209+0000","level":"warn","message":"ignoring extension","gem":"sensu-extensions-history"}
{"timestamp":"2017-07-05T15:05:53.985235+0000","level":"warn","message":"loaded extension","type":"filter","name":"occurrences","description":"filter events using event occurrences"}
{"timestamp":"2017-07-05T15:05:53.985254+0000","level":"warn","message":"loaded extension","type":"filter","name":"check_dependencies","description":"filter events when an event exists for a check dependency"}
{"timestamp":"2017-07-05T15:05:53.985291+0000","level":"warn","message":"loaded extension","type":"mutator","name":"only_check_output","description":"returns check output"}
{"timestamp":"2017-07-05T15:05:53.985310+0000","level":"warn","message":"loaded extension","type":"mutator","name":"ruby_hash","description":"returns ruby hash event data"}
{"timestamp":"2017-07-05T15:05:53.985327+0000","level":"warn","message":"loaded extension","type":"mutator","name":"json","description":"returns JSON formatted event data"}
{"timestamp":"2017-07-05T15:05:53.985343+0000","level":"warn","message":"loaded extension","type":"handler","name":"debug","description":"returns raw event data"}
{"timestamp":"2017-07-05T15:05:53.985359+0000","level":"warn","message":"loaded extension","type":"handler","name":"influxdb-extension","description":"Transforms and sends metrics to InfluxDB"}
{"timestamp":"2017-07-05T15:05:53.985430+0000","level":"info","message":"configuring sensu spawn","settings":{"limit":12}}
{"timestamp":"2017-07-05T15:05:53.985463+0000","level":"debug","message":"setting eventmachine threadpool size","size":22}
{"timestamp":"2017-07-05T15:05:53.985742+0000","level":"debug","message":"connecting to redis","settings":{"host":"127.0.0.1","port":6379}}
{"timestamp":"2017-07-05T15:05:53.986476+0000","level":"debug","message":"connecting to transport","name":"rabbitmq","settings":{"host":"127.0.0.1","port":5672,"vhost":"/sensu","user":"sensu","password":"secret"}}
/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-extensions-influxdb-2.1.0/lib/sensu/extensions/influxdb.rb:34:in `create_config': undefined method `ArgumentError' for #<Sensu::Extension::InfluxDB:0x000000024363e8> (NoMethodError)
	from /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-extensions-influxdb-2.1.0/lib/sensu/extensions/influxdb.rb:83:in `post_init'
	from /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-extension-1.5.1/lib/sensu/extension.rb:19:in `block in initialize'
	from /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/eventmachine-1.2.2/lib/eventmachine.rb:977:in `block in run_deferred_callbacks'
	from /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/eventmachine-1.2.2/lib/eventmachine.rb:974:in `times'
	from /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/eventmachine-1.2.2/lib/eventmachine.rb:974:in `run_deferred_callbacks'
	from /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/eventmachine-1.2.2/lib/eventmachine.rb:194:in `run_machine'
	from /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/eventmachine-1.2.2/lib/eventmachine.rb:194:in `run'
	from /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-0.29.0/lib/sensu/server/process.rb:33:in `run'
	from /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-0.29.0/exe/sensu-server:10:in `<top (required)>'
	from /opt/sensu/bin/sensu-server:22:in `load'
	from /opt/sensu/bin/sensu-server:22:in `<main>'
```

**Comment by majormoses** [comment]
@neyz thanks for the report I will take a look when I have a minute, we announced this yesterday: https://blog.sensuapp.org/community-maintenance-mode-d109e75bcbc4 and I would recommend starting with 0.27 as a new user as there are a lot of breaking changes in 0.29 and 1.0.0 and the maintainers I know are still running either 0.26 or 0.27).The community has not quite caught back up yet.

**Comment by majormoses** [comment]
@luisdavim can you possibly take a look? ,You are way more familiar with this than I am and I am trying to focus on getting the the sensu-plugins org settled down first before dealing with all of this over here as well. If not I will try to carve out some time this weekend or early next week.

**Comment by luisdavim** [comment]
@neyz can you please share your configuration?

**Comment by neyz** [comment]
Thanks for the blog post.

What exactly do you need for configuration ? I pretty much just have the config files listed in the read me but I did play a lot with different influx extensions and handlers and upgraded from an earlier version to 0.29 so maybe I broke something in the process.

I will try again from a clean install

**Comment by luisdavim** [comment]
If you could give us a gist with the configuation you have on your server we could try to reproduce your issu and possibly fix it.

**Comment by luisdavim** [comment]
@neyz did you managed to get this working if yes, can you let us know what you changed to make it work? Even if this was a configuration error I would like the extension to output a more friendly error but I can't reproduce this.

**Comment by Seji64** [comment]
Hi guys,

i just installed this extension and got the same error as neyz. 

> {"timestamp":"2017-07-27T08:40:34.460557+0200","level":"warn","message":"loading extension files from directory","directory":"/etc/sensu/extensions"}
{"timestamp":"2017-07-27T08:40:34.460638+0200","level":"warn","message":"loading extension gem","gem":"sensu-extensions-influxdb","version":null}
{"timestamp":"2017-07-27T08:40:34.460668+0200","level":"warn","message":"requiring extension gem","require":"sensu/extensions/influxdb"}
{"timestamp":"2017-07-27T08:40:34.460691+0200","level":"warn","message":"loaded extension","type":"filter","name":"occurrences","description":"filter events using event occurrences"}
{"timestamp":"2017-07-27T08:40:34.460712+0200","level":"warn","message":"loaded extension","type":"filter","name":"check_dependencies","description":"filter events when an event exists for a check dependency"}
{"timestamp":"2017-07-27T08:40:34.460739+0200","level":"warn","message":"loaded extension","type":"mutator","name":"only_check_output","description":"returns check output"}
{"timestamp":"2017-07-27T08:40:34.460760+0200","level":"warn","message":"loaded extension","type":"mutator","name":"ruby_hash","description":"returns ruby hash event data"}
{"timestamp":"2017-07-27T08:40:34.460778+0200","level":"warn","message":"loaded extension","type":"mutator","name":"json","description":"returns JSON formatted event data"}
{"timestamp":"2017-07-27T08:40:34.460796+0200","level":"warn","message":"loaded extension","type":"handler","name":"debug","description":"returns raw event data"}
{"timestamp":"2017-07-27T08:40:34.460813+0200","level":"warn","message":"loaded extension","type":"handler","name":"influxdb-extension","description":"Transforms and sends metrics to InfluxDB"}
{"timestamp":"2017-07-27T08:40:34.460864+0200","level":"info","message":"configuring sensu spawn","settings":{"limit":12}}
/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-extensions-influxdb-2.1.0/lib/sensu/extensions/influxdb.rb:34:in `create_config': undefined method `ArgumentError' for #<Sensu::Extension::InfluxDB:0x00000002460468> (NoMethodError)
        from /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-extensions-influxdb-2.1.0/lib/sensu/extensions/influxdb.rb:83:in `post_init'
        from /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-extension-1.5.1/lib/sensu/extension.rb:19:in `block in initialize'
        from /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/eventmachine-1.2.2/lib/eventmachine.rb:977:in `block in run_deferred_callbacks'
        from /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/eventmachine-1.2.2/lib/eventmachine.rb:974:in `times'
        from /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/eventmachine-1.2.2/lib/eventmachine.rb:974:in `run_deferred_callbacks'
        from /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/eventmachine-1.2.2/lib/eventmachine.rb:194:in `run_machine'
        from /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/eventmachine-1.2.2/lib/eventmachine.rb:194:in `run'
        from /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-1.0.0/lib/sensu/server/process.rb:33:in `run'
        from /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-1.0.0/exe/sensu-server:10:in `<top (required)>'
        from /opt/sensu/bin/sensu-server:22:in `load'
        from /opt/sensu/bin/sensu-server:22:in `<main>'

Can i provide something else to fix this error?

**Comment by neyz** [comment]
Sorry for the late reply.

I was a little rushed on this project and gave up collecting metrics with sensu and went with the native telegraf road.

Sorry I couldn't be of more help on this issue.

**Comment by luisdavim** [comment]
Hi @Seji64 can you share your configuration?

**Comment by luisdavim** [comment]
one strange thing is that your error message is saying `/sensu-extensions-influxdb-2.1.0` the version of this extension is `0.0.2` I think you are using this one https://github.com/jhrv/sensu-influxdb-extension and not https://github.com/sensu-extensions/sensu-extensions-influxdb

**Comment by luisdavim** [comment]
see here: https://github.com/jhrv/sensu-influxdb-extension/issues/23

**Comment by luisdavim** [comment]
Yes but @jhrv is building that gem from his version of the extension and because of that we can't publish this one with that name.
At the moment we don't have this on rubygems.org so you'll have to build it yourself:
```
git clone https://github.com/sensu-extensions/sensu-extensions-influxdb.git
cd sensu-extensions-influxdb
bundle install
bundle exec rake
bundle exec rake build
```
and then install it with:
```
sensu-install -e pkg/sensu-extensions-influxdb-0.0.2.gem
```
and let me know if that solves your problem.

**Comment by Seji64** [comment]
Okay, that makes sense. You should definitly put that Information in the README.md.

Do i have to build this in the Sensu Ruby enviroment??

**Comment by luisdavim** [comment]
No, you don't have to use the  Sensu Ruby enviroment.

**Comment by Seji64** [comment]
sorry but i got an error installing the compiled package:
```
[root@SIT-MONP03 sensu-extensions-influxdb]# cd /opt/sensu/bin/
[root@SIT-MONP03 bin]# sensu-install -e /root/sensu-extensions-influxdb/pkg/sensu-extensions-influxdb-0.0.2.gem -x http://proxy.it.kle.tt:8080
[SENSU-INSTALL] installing Sensu extensions ...
[SENSU-INSTALL] determining if Sensu gem 'sensu-extensions-/root/sensu-extensions-influxdb/pkg/sensu-extensions-influxdb-0.0.2.gem' is already installed ...
false
[SENSU-INSTALL] Sensu extension gems to be installed: ["sensu-extensions-/root/sensu-extensions-influxdb/pkg/sensu-extensions-influxdb-0.0.2.gem"]
[SENSU-INSTALL] installing Sensu gem 'sensu-extensions-/root/sensu-extensions-influxdb/pkg/sensu-extensions-influxdb-0.0.2.gem'
ERROR:  Could not find a valid gem 'sensu-extensions-/root/sensu-extensions-influxdb/pkg/sensu-extensions-influxdb-0.0.2.gem' (>= 0) in any repository

```

**Comment by luisdavim** [comment]
You probably have to remove the other one first.
BTW, what is `-x http://proxy.it.kle.tt:8080` for?

**Comment by Seji64** [comment]
I already uninstalled the "old" one. -x is for proxy server support.

**Comment by Seji64** [comment]
I managed it to install the local gem via ` /opt/sensu/embedded/bin/gem install --local /root/sensu-extensions-influxdb/pkg/sensu-extensions-influxdb-0.0.2.gem`

Thanks for your help!

**Comment by stevenviola** [comment]
@luisdavim, should we consider changing the name of this extension to `sensu-extensions-influx` so that we can get upload it to rubygems?

**Comment by majormoses** [comment]
@stevenviola I have asked if there is any way we can merge them together: https://github.com/jhrv/sensu-influxdb-extension/issues/23#issuecomment-318445564 if that fails I would opt for something like `sensu-extensions-official` so it is very clear which one is supported by the maintainers of sensu. Once I hear back we can figure out what we can do to make this clearer which will likely include renaming the repo + gem, ISSUE templates, and README changes.

**Comment by luisdavim** [comment]
I agree.

**Comment by runningman84** [comment]
any news here?

**Comment by majormoses** [comment]
we are gonna have to rename the gem + repo. When I have some time I will do that. Do we have any consensus on the name? ping @eheydrick

**Comment by eheydrick** [comment]
sensu-extensions-influxdb2?

**Comment by Seji64** [comment]
I vote for "sensu-extensions-influxdb-offical"

**Comment by majormoses** [comment]
The only reason I am not a fan of adding official (yes I originally proposed it) is that it makes it sound like anything that does not have that is not official which is certainly not the case. I kinda like `sensu-extensions-influxdb2` as it shows that one supersedes the other.

**Comment by joshiegy** [comment]
Hi,

I'm trying to get this to work too - kinda the same issue. Whats the progress on merging this into some sort of "easy-install-mode"?

**Comment by lennartkoopmann** [comment]
+1, this was incredibly confusing

**Comment by majormoses** [comment]
Sorry this kinda fell off my radar but I have gotten much of the work renaming this gem done and am awaiting testing to verify before pushing it to rubygems.

**Comment by triangletodd** [comment]
Hey thanks majormoses. I'm implementing this in a backwards way in my environment now. I look forward to doing it properly. :)

**Comment by majormoses** [comment]
@triangletodd If you'd like to test it you could try pulling my branch and building it with `gem build sensu-extensions-influxdb2.gemspec` and then you can do a `/opt/sensu/embedded/bin/gem install "PATH/TO/GEMFILE/sensu-extensions-influxdb2-$VERSION.gem"` If you confirm it works well I can merge and push to rubygems.

**Comment by triangletodd** [comment]
Will do!

**Comment by majormoses** [comment]
I have pushed the newly renamed version: https://rubygems.org/gems/sensu-extensions-influxdb2

**Comment by luisdavim** [comment]
Awesome, thanks @majormoses

**Comment by triangletodd** [comment]
Oops. My bad @majormoses. I took a week off for Thanksgiving and this fell off my radar. Thanks for your work on this. Much appreciated.
